dist: trusty
sudo: required
services:
- docker

env:
  matrix:
  - ARCH=amd64
  - ARCH=arm64
  - ARCH=armel
  - ARCH=armhf
  - ARCH=i386
  - ARCH=mips
  - ARCH=mips64el
  - ARCH=mipsel
  - ARCH=ppc64el
  - ARCH=s390x
  global:
    secure: SHPeXHefjc6oOdX0p6/NFXnMfvg8it5htQSerScKGQgp6YTUPr0tLyUpXqsQzR5jW5GU58n6dWGa9SR9+ziD9W4vlbG9aTEB6yFBxmyf4Zc8t0QyKL/xesVMa84dtVomiF79iDq95GwuLBgKhDioLMAkyTqQXBDhFuTrGccy/HSyYAnYpTgH8TtiZL4wj8X3znh8cQfocz7r5mL+rS4ypgqbEi/7dabZxTsU7wPm1gUWcXaxzGmDjkIYtF1SQDb0JHP5pr2LjUnitBpqoL56E157brPxkinN818ymNrDIy1V+Lop25RU9u5euoOfbGFW6mMDTRWOLak+GPPHHdSWUsW3lXHrgQeg552El7bOofIebTuyWNv3jQH7ytB6r7Bc4RQXFonzy3VKzrG+iVodHRa1/q8F8AlR/tK/Xp4SqK+8vwtZOmaJ2zAi9www9yzTGINAp+pqTFsYDDcSpnlizUvk+1x8D2uRfe2oZpky5890gdbHbEWA/iOQ8sZiNA0TTrq7iuxCR4vz2ZA8Kv2DqXMjOOUZzAREwPdeeHbqM4b/MxFVZUm55oopEcgZXFlyeMbCu+6NfdGZIZKmv32xSu4sLXf4U45o4BTyqL5z1KcziXweqeYo34qXNnmUoNWZ1E+VrQPmlp9apFDEfhQ9Rq0+2SbclRqjQgcG7pMds14=

branches:
  only: master

addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ devel universe'
    packages:
    - binfmt-support
    - qemu-user-static

script:
- docker build -t laarid/devel:$ARCH devel/$ARCH

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  docker push laarid/devel:$ARCH;
  fi

notifications:
  slack:
    rooms:
    - secure: "AqxV+PQXnDuLA4jeduqPoFWMTm78CyI3+uGf0aB3YQeZw9vjcM5W7TzozH3MjRnw5JkWxyZGULZJkqklZXRnmJf8ify+6dsd2NeEKB8SEiMwrjaRLwc4/roVCArEJyhhU2o0ZvK/iQitoaC6PBhPcTiockv2eNj7Eqw1krdwnFEwDQ5Qn5ehr6EkjuUd8VdqaUMs/kIGNv7I67Ahg1/a2CHU8W8MmO00B6uZ0UAIDdJhSn5YFNr9wseSKlFXP2aQ9nmyC17q24HMk5rVkkts45Kzp102CPrh9ycZqBsKJjsxUqxfYq2DAq/Tk24AzWKNZQMM1jpwPqom/Tl580TtvfDC1E50LBUtEZweE9dIOtMKQ97TFa/hWrm5l+B4dX9rN8Yy9ifGsxhNmF0PWR8Hj3+kJh4pjfCdGQsvb2OLM30yWSU/SAkAlwZUjeTWvsQ9WVlI8130ltW47AgSfCVwx3inCMZie/fpnpjLBTKIrzpsf6dRvkVRtUIKq3YrpDsmMF7dp/2tj+rDKnq18bHDyPFy9QS0Gls6pIUlKxJZJMXUK/lB3MjC6ByB2kYv+P6Iugt8/F3U2YA8VqrB0QcZpZqxlPGj7awvJqxO6G4i3AEEfpN/KSAPXnx7VKUwLVMmKogKo6P7aQxgIGofo/r/qfRSD2+Qa4HRPolHXmRUvKA="
