dist: trusty
sudo: required
services:
- docker

env:
  matrix:
  - JOB_DOCKERFILE_DIR=amd64 JOB_ARCH=amd64
  - JOB_DOCKERFILE_DIR=arm64 JOB_ARCH=arm64 JOB_QEMU_ARCH=aarch64
  - JOB_DOCKERFILE_DIR=armel JOB_ARCH=armel JOB_QEMU_ARCH=arm
  - JOB_DOCKERFILE_DIR=armhf JOB_ARCH=armhf JOB_QEMU_ARCH=arm
  - JOB_DOCKERFILE_DIR=i386 JOB_ARCH=i386
  - JOB_DOCKERFILE_DIR=mips JOB_ARCH=mips JOB_QEMU_ARCH=mips
  - JOB_DOCKERFILE_DIR=mips64el JOB_ARCH=mips64el JOB_QEMU_ARCH=mips64el
  - JOB_DOCKERFILE_DIR=mipsel JOB_ARCH=mipsel JOB_QEMU_ARCH=mipsel
  - JOB_DOCKERFILE_DIR=ppc64el JOB_ARCH=ppc64el JOB_QEMU_ARCH=ppc64le
  - JOB_DOCKERFILE_DIR=ppc64el-next JOB_ARCH=ppc64el JOB_QEMU_ARCH=ppc64le JOB_SKIP_TAG=1
  - JOB_DOCKERFILE_DIR=s390x JOB_ARCH=s390x JOB_QEMU_ARCH=s390x
  global:
    secure: "NGpkPyR+Yw5ibEeGuXDm3jv5QlDNio8U+n5q8QjpKJMk66Y7W0zWgHNkS6gZ07Fk9MHwxHF+GA+4xoN1DFRG1qr7ERhlXBq636pVpU2H3vOCe1CWHdU7ZrEoxjzNLQOcHx+BL7/etQKTdEssEj5AQMmIiweQmqJs9EBGXxJdUsZMNCGN/5Xnht0HZ8QiH+salR1ra3vIHerm8XYuIZeozA2Zu8q39inh9s5MYqCbQzFnjtBxlbeaKhDU2cC1lUKWaKBhzNtuaCx3OX56R1a9QmQxeqUcJ57a0YWobQqUmKrluRhfM65UN9+PCP3rwHPhE/RGFIV/V2Kxlr7FViJPEABZNMbyyiz+KaUS6kugdg8RD3r79IZZ7NIP73wBY7BY98RZSb1Hhg2nfwNoZewc/Jba0fpzYXoiaG8M0tGRRV5EQfqL6iIO0QXVxM6UnOTJQjlbdVlu7zuQpJQabRwEVMIzfbebjaHtPMOQZAcBDvtEz9heJOFWqnQnbIjMSjR1zexNIgNHbQbynRRfuyXoToRoc5jJDOKWJwHb06RIlAgdFQXnvj1JkiOHTJ7AKLZZg83tHLjZEvwLcIKdhbZ4850D5TBiKADDqrlDIoYetZuCiCSkHGRY7NfAgDbPV7CPtt3IAAEu2c8DxadC5MmynJv84reRbzgQt06ILIvKQZU="

matrix:
  fast_finish: true
  allow_failures:
  - env: JOB_DOCKERFILE_DIR=ppc64el-next JOB_ARCH=ppc64el JOB_QEMU_ARCH=ppc64le JOB_SKIP_TAG=1

branches:
  only: master

addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ devel universe'
    packages:
    - binfmt-support
    - qemu-user-static

script:
- dpkg -s qemu-user-static
- docker build -t laarid/native-build:${JOB_ARCH} ${JOB_DOCKERFILE_DIR}
- if [ -n "${JOB_QEMU_ARCH}" ]; then
    docker run --rm laarid/native-build:${JOB_ARCH} /usr/bin/qemu-${JOB_QEMU_ARCH}-static --version;
  fi
- git clone -o laarid https://github.com/laarid/package_android-bionic.git test
- docker run --rm
    --volume ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}
    --workdir ${TRAVIS_BUILD_DIR}/test
    laarid/native-build:${JOB_ARCH}
    /bin/sh -c "mk-build-deps --host-arch ${JOB_ARCH} --install --remove --root-cmd sudo --tool 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y' && dpkg-buildpackage --host-arch ${JOB_ARCH} -i -us -uc -b"

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" -a -z "${JOB_SKIP_TAG}" ]; then
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
    docker push laarid/native-build:${JOB_ARCH};
  fi

notifications:
  slack:
    rooms:
    - secure: "D7zKMkeCkg/7uhmDJrAVlqfcXjQJEExsYvgQI2RYXXrlRCCE9PK3OzFCGXejCizDQ8cFHEuDeH6zM0x09u+a6jNThrsvsnsa1/BKVP1wos9DqaHrO6zF5Gmem7koeud+c7CzHsiJIErwQdHbShCBU4m/Pb/K1Hy4ExqRBuJtWkWhxi8QjRKgYjE0RdknWXmuNrEjbdOh046DhWaT/lA7BH1BoXBm8RKvIaIrrBpgc09TzF80IltCDbgFPq8rdj8Z9Oe0hzJNZGYbRUBFrSHtnFKpr+BAWQiWVGVZDZwTMSnPSVE5uWq5KQ3VTNOGsFM+HDVl5M+TgGSCcl72nRRlloe24e+FseofFm1HR4IcVKBNez6lANiQk99fMmXcOw408vaaaP4p2meNLwK7mqEvM51do+y2Woa/YtGobtMsAyWCs+4CBQjWWQsoT/Ih24M3xJ2qItSTGHhzc4yTSiCsGAPxbhk8qYcv79H2AJvnAC06ZDRP+U5L4vWCKA1k0zTYd0j/TbPZBZYYRYBPMWaF7ZCL2Rani8BsfZuvRyOBtex+n61GqyNCnhCyNILmPKi55xRBN0gOvAUoDw/kJGMJm+oT1OcFUnusLguU07JRzEM3BVzyDj1rxPKCJ38gQNIWhs0wWAPTRinqcwiftGRTluysvS09z8FFd5yA4cF4q/Q="
